import { Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "../@/components/ui/sonner"
// Font Setup
import TopLoadingBar from "../components/TopLoadingBar";
const outfit = Outfit({ subsets: ["latin"] });

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <ClerkProvider signInUrl="/sign-in">
      <html lang="en">
        <head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </head>
        <body className={outfit.className}>
        <TopLoadingBar />
          <Provider>{children}</Provider>
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  );
}
